name: mabs-x84_64

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 960
    steps:
      - uses: actions/checkout@v4
      - name: Extract Cache
        run: |
          if (Test-Path "D:/cache.tar.xz") {
            New-Item -ItemType Directory -Path msys64/home/CCOM-9020M$/.ccache
            tar -xf D:/cache.tar.xz -C $(Resolve-Path msys64/home/CCOM-9020M$/.ccache)
          }

      - name: Get ini file
        run: Invoke-WebRequest https://raw.githubusercontent.com/xdeadboy666x/mab/refs/heads/master/build/media-autobuild_suite.ini -OutFile build/media-autobuild_suite.ini

      - name: Replace do_prompt
        run: sed -i 's/do_prompt /echo /g' build/media-suite_helper.sh build/media-suite_compile.sh

      - name: Compile the suite
        shell: cmd
        run: media-autobuild_suite.bat

      - name: Tar cache
        run: |
          if (Test-Path "msys64/home/CCOM-9020M$/.ccache") {
            tar -cf D:/cache.tar.xz --no-acls -C $(Resolve-Path msys64/home/CCOM-9020M$/.ccache) .
          }
          
      - uses: actions/upload-artifact@v4 # Only on distributable builds
        with:
          name: mabs-x84_64
          path: local64
