name: Media Autobuild Suite (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install PSScriptAnalyzer module
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop

      - name: Get list of rules
        shell: powershell
        run: |
          Get-ScriptAnalyzerRule

      - uses: actions/checkout@v4
        with:
          path: mab  # Clones repo into D:\a\media-autobuild_suite\media-autobuild_suite\mab

      - name: Move to D:\a
        run: |
          Move-Item -Path mab -Destination ../mab  # Moves "mab" to D:\a\mab

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
        
      - name: Restore cache (build & msys64)
        uses: actions/cache@v4
        with:
          path: |
             ../mab/build
             ../mab/msys64
          key: ${{ runner.os }}-mab-${{ hashFiles('mab/media-autobuild_suite.bat') }}
          restore-keys: |
             ${{ runner.os }}-mab-

      - name: Run media-autobuild_suite.bat
        shell: powershell
        run: |
          cd ../mab
          cmd.exe media-autobuild_suite.bat
        env:
          GH_TOKEN: ${{ secrets.TOKEN_REPO }}
